### ISSUE TITLE
Index was out of range. Must be non-negative and less than the size of the collection. 

### ISSUE THREAD

**Issue by suzhouhu** [stoneflyop1/NetGltf#6]
![图片](https://user-images.githubusercontent.com/23079693/203199540-bb44c6c2-baed-4a70-b866-4a7a84de9bf9.png)
[model.zip](https://github.com/stoneflyop1/NetGltf/files/10062415/model.zip)
System.ArgumentOutOfRangeException
  HResult=0x80131502
  Message=Index was out of range. Must be non-negative and less than the size of the collection. 
  Source=System.Private.CoreLib
  StackTrace:
   at System.ThrowHelper.ThrowArgumentOutOfRange_IndexException()
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Obj2Gltf.WaveFront.Group.EndList(List`1 ranges, UInt32 end) in C:\Users\Administrator\Desktop\NetGltf-master\src\Obj2Gltf\WaveFront\ObjData.cs:line 72
   at Obj2Gltf.WaveFront.Group.End(Counter counter) in C:\Users\Administrator\Desktop\NetGltf-master\src\Obj2Gltf\WaveFront\ObjData.cs:line 63
   at Obj2Gltf.GroupBuilder.Start(String input) in C:\Users\Administrator\Desktop\NetGltf-master\src\Obj2Gltf\ObjParser.cs:line 31
   at Obj2Gltf.ObjParser.<>c__DisplayClass0_0.<Parse>b__0(String key, IList`1 args) in C:\Users\Administrator\Desktop\NetGltf-master\src\Obj2Gltf\ObjParser.cs:line 136
   at Obj2Gltf.TextParser.Lex(StreamReader reader, Action`2 action) in C:\Users\Administrator\Desktop\NetGltf-master\src\Obj2Gltf\TextParser.cs:line 48
   at Obj2Gltf.ObjParser.Parse(String inputFile, Encoding encoding) in C:\Users\Administrator\Desktop\NetGltf-master\src\Obj2Gltf\ObjParser.cs:line 85
   at Obj2Gltf.ModelConverter.Run() in C:\Users\Administrator\Desktop\NetGltf-master\src\Obj2Gltf\ModelConverter.cs:line 58
   at Csharp.obj2gltf.Form1.Converter_GLB_Tests3() in D:\Csharp.obj2gltf\Form1.cs:line 65
   at Csharp.obj2gltf.Form1.button1_Click(Object sender, EventArgs e) in D:\Csharp.obj2gltf\Form1.cs:line 72
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at Csharp.obj2gltf.Program.Main() in D:\Csharp.obj2gltf\Program.cs:line 20

**Comment by stoneflyop1** [comment]
> ![图片](https://user-images.githubusercontent.com/23079693/203199540-bb44c6c2-baed-4a70-b866-4a7a84de9bf9.png) [model.zip](https://github.com/stoneflyop1/NetGltf/files/10062415/model.zip) System.ArgumentOutOfRangeException HResult=0x80131502 Message=Index was out of range. Must be non-negative and less than the size of the collection. Source=System.Private.CoreLib StackTrace: at System.ThrowHelper.ThrowArgumentOutOfRange_IndexException() at System.Collections.Generic.List`1.get_Item(Int32 index) at Obj2Gltf.WaveFront.Group.EndList(List`1 ranges, UInt32 end) in C:\Users\Administrator\Desktop\NetGltf-master\src\Obj2Gltf\WaveFront\ObjData.cs:line 72 at Obj2Gltf.WaveFront.Group.End(Counter counter) in C:\Users\Administrator\Desktop\NetGltf-master\src\Obj2Gltf\WaveFront\ObjData.cs:line 63 at Obj2Gltf.GroupBuilder.Start(String input) in C:\Users\Administrator\Desktop\NetGltf-master\src\Obj2Gltf\ObjParser.cs:line 31 at Obj2Gltf.ObjParser.<>c__DisplayClass0_0.b__0(String key, IList`1 args) in C:\Users\Administrator\Desktop\NetGltf-master\src\Obj2Gltf\ObjParser.cs:line 136 at Obj2Gltf.TextParser.Lex(StreamReader reader, Action`2 action) in C:\Users\Administrator\Desktop\NetGltf-master\src\Obj2Gltf\TextParser.cs:line 48 at Obj2Gltf.ObjParser.Parse(String inputFile, Encoding encoding) in C:\Users\Administrator\Desktop\NetGltf-master\src\Obj2Gltf\ObjParser.cs:line 85 at Obj2Gltf.ModelConverter.Run() in C:\Users\Administrator\Desktop\NetGltf-master\src\Obj2Gltf\ModelConverter.cs:line 58 at Csharp.obj2gltf.Form1.Converter_GLB_Tests3() in D:\Csharp.obj2gltf\Form1.cs:line 65 at Csharp.obj2gltf.Form1.button1_Click(Object sender, EventArgs e) in D:\Csharp.obj2gltf\Form1.cs:line 72 at System.Windows.Forms.Control.OnClick(EventArgs e) at System.Windows.Forms.Button.OnClick(EventArgs e) at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent) at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks) at System.Windows.Forms.Control.WndProc(Message& m) at System.Windows.Forms.ButtonBase.WndProc(Message& m) at System.Windows.Forms.Button.WndProc(Message& m) at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam) at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg) at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData) at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context) at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context) at System.Windows.Forms.Application.Run(Form mainForm) at Csharp.obj2gltf.Program.Main() in D:\Csharp.obj2gltf\Program.cs:line 20

@suzhouhu 
fixed, see #10
